### ISSUE TITLE
some monster stats can not be entered in the sheet

### ISSUE THREAD

**Issue by Pusikas** [wesbaker/roll20-character-sheets#8] opened 2020-05-26 11:34 UTC
What I found out while entering the stats for a Giant Centipede:

They have less than 1HD. I can enter 0.5. The sheet correctly calculates the avergage HP as 2. But my browser (Chrome) keeps telling me to enter a valid value. Also, the sheet does not automatically calculate the saves in this case.

They deal no damage. I entered a "0" in the damage field. Minimum damage is still 1, though. When I try to leave it empty, it gets replaced by 1d6+1. When I enter a text, then I can no longer roll the attack.

~~Entering the Saves by hand seems to work at first. When closing and re-opening the Centipede's sheet, the get resetted to 0, though.~~

~~UPDATE: The Saves keep resetting to 0, even when I enter a "1" as the HD.~~

UPDATE 2: The monster's encounter speed is not a value that can be referenced by a token - only the exploration speed is. Having the encounter speed on a token might come in handy sometimes.

~~UPDATE 3: When I to enter "Fighter" as a class on the character tab, then I get automagically filled Saves on the monster tab. This is kinda confusing. They ignore the monster's HD, tho.~~

--- 

Issues Found:

- [x] Monster's encounter speed is unavailable to tokens
- [x] Giant Centipedes deal no damage according to stat block, does minimum damage still happen?
- [ ] Chrome error with HD of 0.5?

Saving Throw issues moved to #10

**Comment by wesbaker** [comment] 2020-05-26 13:45
> They have less than 1HD. I can enter 0.5. The sheet correctly calculates the avergage HP as 2. But my browser (Chrome) keeps telling me to enter a valid value. 

I'll take a look, sounds like a case I didn't account for.

> Also, the sheet does not automatically calculate the saves in this case.
> 
> Entering the Saves by hand seems to work at first. When closing and re-opening the Centipede's sheet, the get resetted to 0, though.

The saves reseting is due to what I put into automatically calculate certain values for characters. It sounds like I need to separate a monster's saves from the character's saves.

It looks like monsters have their own saving throw table _as well_ as using saves from various classes at certain levels. Here's what I'm thinking:

- Create a select/dropdown for "Saves as" and fill it with Monster plus the seven classes in the base book _plus_ Custom
- It'll use the correct saves, both from the endpapers and from the classic fantasy book
- If you select Custom, nothing will be automatically calculated
- If you select one of the seven classes, I'll show another input that allows you to set the level of the class (e.g. saves as Fighter 3)

That'll take a bit of time for me, but how does that sound?

**Comment by Pusikas** [comment] 2020-05-26 15:59
Sounds great!

Oh, and btw: at least in the version currently on Roll20, the character name and the monster name aren't linked. I still have to enter a monster's name in the character tab- Otherwise, I don't see the monster's name in the Journal.

**Comment by wesbaker** [comment] 2020-05-26 16:00
> I still have to enter a monster's name in the character tab- Otherwise, I don't see the monster's name in the Journal.

Yeah, they merged it yesterday and the fixes typically hit on Tuesday, but I have no idea (or control over) when that happens.

**Comment by Pusikas** [comment] 2020-05-27 09:49
>     * Create a select/dropdown for "Saves as" and fill it with Monster plus the seven classes in the base book _plus_ Custom
> 

I just noticed, that most monsters with ½HD use the "Normal Human" saving throws. So do most NPCs and non-fighting beasts, like mules and such. You may want to add this set of saves as an 8th option.

**Comment by wesbaker** [comment] 2020-05-27 14:05
> The sheet correctly calculates the avergage HP as 2. But my browser (Chrome) keeps telling me to enter a valid value.

Can you show me a screenshot of what you're talking about? When I enter 0.5 as the HD, I see the Average HP calculated correctly, but I don't see any error in Chrome. I do notice that you can't calculate the HP by clicking the HD button. I can fix that, but it'd be a big fix for a small and infrequent problem.

> They deal no damage. I entered a "0" in the damage field. Minimum damage is still 1, though. When I try to leave it empty, it gets replaced by 1d6+1. When I enter a text, then I can no longer roll the attack.

You need _a_ value in there. The `1d6+1` is a placeholder, but the value isn't actually there. If those placeholders are confusing I could remove them. Instead, just put the value `0` in that space, or `1` since that's the minimum anyways. And maybe I'm wrong here, but I'm working off the assumption that both players and monsters have a minimum damage of 1 [per the rules](https://oldschoolessentials.necroticgnome.com/srd/index.php/Combat#Rolling_for_Damage):

> Minimum damage: An attack which hits always deals at least one point of damage, even when damage modifiers reduce the number rolled to 0 or less.

Is that not the case for monsters?

**Comment by Pusikas** [comment] 2020-05-27 17:39
> PC attacks: Inflict 1d6 damage. Damage
of melee attacks is modified by STR.

>Monster attacks: Deal the damage indicated
in the monster’s description.

>Minimum damage: An attack which hits
always deals at least one point of damage,
even when damage modifiers reduce the
number rolled to 0 or less.

That's from the rules. But the Giant Centipede lists this as attack:
> Att 1 × bite (poison)

I am not sure what to make of this. The rules sound like they might be doing one point of damage, even tho there isn't even a damage die. Then again, the rules talk about a rolled number that can't be reduced to 0 or less. And the centipede doesn't roll. 😕

**Comment by wesbaker** [comment] 2020-05-27 17:48
> Then again, the rules talk about a rolled number that can't be reduced to 0 or less. And the centipede doesn't roll.

That's a good point. Here's my plan:

- Attacks from Characters will still have a minimum of 1 damage
- Attacks from Monsters will *not* have that minimum, so entering 0 will result in no damage, but it will show it, which I think is still valuable

<img width="260" alt="Screen Shot 2020-05-27 at 1 50 21 PM" src="https://user-images.githubusercontent.com/15715/83054834-0404a680-a021-11ea-9f47-b03293cbe5f0.png">

**Comment by Pusikas** [comment] 2020-05-27 17:54
I looked them up in the old B/X book and their entry explicitly states that their attacks don't deal any damage. So by freak accident the first monster I tried to use with the new character sheet is one that breaks the rules. :)

**Comment by wesbaker** [comment] 2020-05-27 17:55
Which is great! Find more rule breakers so we can keep improving the sheet.

**Comment by Pusikas** [comment] 2020-05-27 18:27
I just saw that an attack's description is only printed for characters, not for monsters. Would be great to get that for monsters as well. AT least as an option.

**Comment by wesbaker** [comment] 2020-05-27 18:52
> Would be great to get that for monsters as well. AT least as an option.

That should be there...I'll add it in.

**Comment by wesbaker** [comment] 2020-05-27 18:58
@Pusikas any further debugging on the Chrome error or do you have a screenshot of it? I can't reproduce it.

**Closed as completed** 2020-06-01 17:18 UTC
Labels: bug

**Comment by DementedAvenger** [comment] 2021-03-17 04:02
Related: when I try to roll HP for a creature of 1/2 HD, it just displays 0.5 (the value I have for the HD). It doesn't display the average HP as anything but 0 when I enter this.

**Comment by wesbaker** [comment] 2021-03-17 13:59
> Related: when I try to roll HP for a creature of 1/2 HD, it just displays 0.5 (the value I have for the HD). It doesn't display the average HP as anything but 0 when I enter this.

That makes sense as it takes the value you put into the HD and rolls `Xd8` and I doubt Roll20 knows what to do with `0.5d8`. I can look into it at some point, but my recommendation would be to manually put in the HP values for now.
